### ISSUE TITLE
pinterest app

### ISSUE THREAD

**Issue by upcomingtradera** [pinterest/api-quickstart#101]
The pinterest documentation is written well, how long does the app stays in access is pending before it can be approved?

**Comment by davidchaiken** [comment]
Hello and thanks for your interest in developing an app for the Pinterest API! At the moment applications tend to be reviewed within a week.  Once your application has been reviewed you’ll receive an email notification of your application’s status. If you have further questions about a specific application you can create a ticket through our [help center](https://help.pinterest.com/en/contact). (Click on Pinterest API and Developer Tools. Then click on API Access and hit the Continue button. Then click on Application Status and hit the Continue button. Then, fill out the form and hit the Continue button.)
