### ISSUE TITLE
v5 organic improvement suggestions

### ISSUE THREAD

**Issue by JacobFunnel** [pinterest/api-quickstart#104]
While migrating to v5 of the API we noticed that some fields were missing and got great assistance in addressing that (https://github.com/pinterest/api-quickstart/issues/89) which is really appreciated! Now we have been using v5 for some time and would like to share our understanding of the state of Pinterest Organic and feedback what we think would be good improvements for the future.

#### User account level daily organic data

[user_account/analytics](https://developers.pinterest.com/docs/api/v5/#operation/user_account/analytics) is a very fast and easy way to fetch high level aggregate organic performance data per day. This endpoint is useful for us for creating an overview report on this level. Great stuff!

#### Pin level daily organic data

To get detailed organic performance data for pins, per day, we can use [/pins](https://developers.pinterest.com/docs/api/v5/#operation/pins/list) to fetch metadata for all existing pins and then for every pin we can call [pins/{pin_id}/analytics](https://developers.pinterest.com/docs/api/v5/#operation/pins/analytics) to get organic performance metrics on a daily basis.

This seemingly works to get only organic data and not miss any pins, but this leads to us having to make a lot of API calls to find out the latest pin activity for the past 7 days. The absolute majority of the calls will not generate any data and will only unnecessarily burden your systems. Since we do not know what pins had any activity, we need to query the analytics endpoint for every single one of the pins. We ran into rate limiting issues when we tried to fetch organic data in this way.

[analytics/top_pins](https://developers.pinterest.com/docs/api/v5/#operation/user_account/analytics/top_pins) only returns the top 50 pins and since v5 does not include pin meta data. So going this route will potentially miss some data and still requires additional requests to get pin meta data. Top pins doesn't include the `USER_FOLLOW` metric either, which a lot of our clients are missing from v3, and we we would need to call [pins/{pin_id}/analytics](https://developers.pinterest.com/docs/api/v5/#operation/pins/analytics) for each relevant `pin_id` to retrieve `USER_FOLLOW` which would again burden your API a lot.

### Feedback

Ideally we would like to query for all pins that have any organic metrics for a specified date range. I.e. ask questions like “what pins had impressions (or any organic metrics, really) the last 7 days?” and ideally get both metadata and metrics for those pins in one response from one endpoint. This would fit our use case the best while burdening your servers the least. This data would then be possible to aggregate to the [user_account/analytics](https://developers.pinterest.com/docs/api/v5/#operation/user_account/analytics) without missing any relevant data points.

**Comment by davidchaiken** [comment]
Thanks very much for your feedback! I understand what you're saying. Would you be willing to submit it via [this official feedback form](https://docs.google.com/forms/d/e/1FAIpQLSefzROl8sgvjHuM7_7f08d7y9eDGAR9VDhP4Tm2nc8GNq9r8w/viewform)? Once you do that, I can follow through internally to make sure that your comments about Pin analytics are being considered by the appropriate product managers.

**Comment by JacobFunnel** [comment]
Thanks @davidchaiken, I've submitted the form!

**Comment by davidchaiken** [comment]
Thanks, @JacobFunnel.

The Pinterest development team says that they "love the level of detail in your feedback!" There's some good news about recent improvements in our API in areas that address at least some of your needs. For example, we recently made an update to the [GET/Pin endpoint](https://developers.pinterest.com/docs/api/v5/#operation/pins/get) which should help address your concern.  You're now able to request `pin_metrics` when calling this endpoint and get the pin's lifetime and last 90 day performance returned. We hope that this feature reduces your need to additionally call the GET/Pin Analytics endpoint for summary metrics.

There's at least one other related feature that should be launching soon. I'll clarify the timing and get back to you -- soon, I hope.

**Comment by davidchaiken** [comment]
Hi, @JacobFunnel. Here's the rest of the response from the development team at Pinterest.

1. As of this week, the [LIST/Pin endpoint](https://developers.pinterest.com/docs/api/v5/#operation/pins/list) supports the `pin_metrics` parameter. So, you can get analytics for a set of pins from a single API call.
2. The idea of only returning data for pins that have shown change is an interesting concept. They are thinking about what it might take to implement this suggestion.

That's all of the information that I can provide for now, so I'm closing this issue.

**Comment by JacobFunnel** [comment]
Hi @davidchaiken! Thanks you for helping us share our feedback and thanks to the development teams for making these improvements! We will look forward to trying out these new features. Please let me know if point 2. makes it into an API update in the future, that would be exciting stuff! :)

**Comment by davidchaiken** [comment]
Will do! Thanks for your feedback and partnership.
