### ISSUE TITLE
Support for the terms endpoint?

### ISSUE THREAD

**Issue by matthewcummings** [pinterest/api-quickstart#108]
Hi, two questions:

- Will you be adding support in this repo for the `terms` endpoints e.g. https://developers.pinterest.com/docs/api/v5/#operation/terms_related/list ?
- I've tried using this endpoint via `curl` but it's not working for me currently. Could that be because my business account does not yet have an Ads account?

**Comment by davidchaiken** [comment]
Good question. I put this support on my to-do list and will have a look at support.

**Comment by davidchaiken** [comment]
I started working on this request. The nodejs code is available in this branch: https://github.com/pinterest/api-quickstart/compare/dc_PINDP-2736

**Comment by davidchaiken** [comment]
Pull Request #109 has the code.

**Comment by davidchaiken** [comment]
Done.
