### ISSUE TITLE
Is there a way to upload multiple local images to pinterest?

### ISSUE THREAD

**Issue by ravyrafael** [pinterest/api-quickstart#111]
Hi,
I'm trying to find a way to upload multiple images without using the Pinterest mobile app. 
When I try to upload on the web, the images decrease in resolution.

My last try will be to use Pinterest api but I didn't find anything that helps me with that.

**Comment by davidchaiken** [comment]
Thanks for the feedback! If the API doesn't work for you, please consider creating a ticket through our [help center](https://help.pinterest.com/en/contact). (Click on Pinterest API and Developer Tools. Then click on API Technical Support and hit the Continue button. Then click on Pinterest API v5 and hit the Continue button. Then, fill out the form and hit the Continue button.) You can also submit feedback through the form linked at the bottom of [this page for developers](https://developers.pinterest.com/docs/new/help-and-feedback/).
