### ISSUE TITLE
You can't connect an app!

### ISSUE THREAD

**Issue by pearcircuitmike** [pinterest/api-quickstart#126]
You can't connect an app because when you try to create one, the image upload fails. This is a required field so it never succeeds and you can never even create an app.

**Comment by pearcircuitmike** [comment]
![Screen Shot 2024-07-21 at 12 55 57 PM](https://github.com/user-attachments/assets/02dc234e-2569-4917-89fd-b0e601cd0fed)
just spins forever, nice

**Comment by davidchaiken** [comment]
Sorry to hear that you had a problem with the [Connect App|https://developers.pinterest.com/apps/connect/] screen. I just tried it, and it worked for me. I'd appreciate it if you would give it another try. Thanks!

<img width="426" alt="Screenshot 2024-07-21 at 4 08 49 PM" src="https://github.com/user-attachments/assets/29f55c8c-e413-47fc-881c-e8b8dd147ec3">

**Comment by pearcircuitmike** [comment]
No, wrong, it does not work still. There's some issues with your service.
<img width="1461" alt="Screen Shot 2024-07-22 at 10 51 48 AM" src="https://github.com/user-attachments/assets/d4b18857-17ce-473a-847c-42b58cfee5d4">

**Comment by pearcircuitmike** [comment]
You also don't correctly maintain state, I've had to agree to these terms about 5-6 times.
![Screen Shot 2024-07-22 at 10 53 24 AM](https://github.com/user-attachments/assets/a1671c89-eb11-4745-800d-37d9effca3ed)

**Comment by davidchaiken** [comment]
Thanks for the feedback. I'll check with the development team to see why this is happening.

**Comment by davidchaiken** [comment]
I'll also file a bug on the image upload. Thanks!

**Comment by davidchaiken** [comment]
Just wondering... How big is the image that you're trying to upload? And would you be willing to share it with me?

**Comment by pearcircuitmike** [comment]
![robot3](https://github.com/user-attachments/assets/82aacdaf-a535-4f20-967b-3fec9d76e79d)
here it is, just 234kb. I've tried a number of different of images, and all fail.

**Comment by davidchaiken** [comment]
Thanks. I can't reproduce the bug with that image, but really appreciate your patience. We definitely aim for developers to have a better experience.

If you're willing, it would be helpful if you would open a ticket at https://help.pinterest.com/en/contact.

Click on Pinterest API and Developer Tools, then Developer Site, then Site Support. Just enter "1234567" as the AppID on the "Who are we helping?" screen, and enter the details. Once you support the ticket, I'll get in touch (via email and our customer support system) so that we can get to the bottom of this problem.

**Comment by pearcircuitmike** [comment]
I did that yesterday, and no one replied. I don't have a ticket number but I received a confirmation it was submitted via email on Sun, Jul 21, 1:56 PM

**Comment by davidchaiken** [comment]
I found the ticket and will follow up on that channel. Thanks again for your patience! Your feedback is really valuable.

**Comment by davidchaiken** [comment]
Thanks again for reporting this issue. We haven't been able to reproduce the image upload failure, so we have removed the requirement to upload an App icon to create an App.
