### ISSUE TITLE
env issue please help

### ISSUE THREAD

**Issue by Primav1022** [pinterest/api-quickstart#128]
This environment always cannot be configured. When executing this code, an error will be reported: 

> $.../common/scripts/api_env.
> /usr/bin/bash.
> Please create an application credentials file here:
> /usr/bin/api_app_credentials.
> For more information, see the "Put your app ID and secret" section of the top-level README in this repo. 

However, I have already set this ID and secret.

**Comment by davidchaiken** [comment]
Can you say more about your configuration? This is pretty straightforward shell code.

Also, it's `. ../common/scripts/api_env` not `.../common/scripts/api_env`.

**Comment by davidchaiken** [comment]
Please try this branch to see if it fixes your problem: https://github.com/pinterest/api-quickstart/tree/dc_fix_issue_128

**Comment by Primav1022** [comment]
Yeah thanks, we found that problem and i would say there were a lot of different between Win and Mac, for another example the makefile in python>tests.

**Comment by davidchaiken** [comment]
I see. Any chance you would consider submitting a pull request with Windows support? Alternatively, can you say a bit more about what Windows environment you're using? For example, what version of WSL are you using (assuming you're using WSL)?

**Comment by Primav1022** [comment]
Yeah ok, there's a lots of different,,, I will answer this question in future and btw I was wondering if pinterest api can get the public picture??(Like I would like to get the related picture from public pin when users input their search keywords? that's seems a very simple requirements) I have tried a lot of times but it seems can just get the picture what user's or the account already have? That's not good for us to get inspirations.... or what's wrong i have done? can give me some helps?

**Comment by Primav1022** [comment]
![image](https://github.com/user-attachments/assets/4cc6f870-4907-4597-b45f-3b28f78132b9)
emmmmm here's response 
> $python get_pin.py -p 1147643917565480716
,
 it seems it didn't read the ACCESS_TOKEN, is this caused?

**Comment by davidchaiken** [comment]
I'm not quite sure what you mean by "public picture." If you're referring to an account's profile picture, the OAuth tutorial [here](https://pinterest-oauth-tutorial.glitch.me/) shows how to get it.

If you're referring to the Search tab and/or the "More to explore" features in the Pinterest app, I can submit a feature request. Can you say a bit more about the use case you're trying to support?

**Comment by Primav1022** [comment]
Thanks for your kindly response, I mean the second one, search tab. Actually i dont know how you define the bussiness account but we guys(designer) are just using pinterest for user to get what they want in VISUAL level and knowing the related picture characteristics for knowing their like and generate something based on their like, for customization and design for their own, and we trying to develop tools for this pipeline. We guys using pinterest for grabing the cutting-edge aesthetic information/inspiration something like this. Because you know that not every user already have something in their boards or pin if they have a new task in life or they face something new, so they absolutely need to search for new.^_^

**Comment by davidchaiken** [comment]
Thanks for describing your use case! I'll pass the request along to our product team.

**Comment by Primav1022** [comment]
Waiting for you………and now we are not using your API and get your pictures from mock search…………but i think it is unfair for bussiness account and API user also it was so bad quality.

**Comment by davidchaiken** [comment]
Hello! I forwarded your feedback to your product team. I think that we understand your use case, but the decision to provide API access to search capabilities is a big one for us.

In the meantime, I'm going to close this issue because this topic isn't related directly to the code in this repo.
