### ISSUE TITLE
Pins and boards are not visible for other accounts!

### ISSUE THREAD

**Issue by Pyswann** [pinterest/api-quickstart#129]
I have developed a script using Python for uploading pins. I used the sandbox api for that, but the issue is, boards and pins are not visible or accessible for other accounts. And of course, i set the privacy for the boards "Public"

Just, i can see those pins and boards. How can i make those pins and boards visible for all?

**Comment by davidchaiken** [comment]
Hello! Does your app have Trial Access or Standard Access. If your app has Trial Access, the Pins and boards you create will only be visible to you (the creator). For more information, please read [this documentation page](https://developers.pinterest.com/docs/getting-started/access-tiers/).
