### ISSUE TITLE
Auth fails on write but not on read

### ISSUE THREAD

**Issue by muezz** [pinterest/api-quickstart#130]
I have followed the guidelines in the docs as well as the code in this repository. But my logic fails when I try to write a board but works fine on read. 

Here is the code for getting an access token:
```typescript
const getAccessToken = async () => {
  const accessTokenExpiresAt = await redis.get<number>(
    "PINTEREST_ACCESS_TOKEN_EXPIRES_AT"
  );
  if (
    accessTokenExpiresAt != null &&
    accessTokenExpiresAt > dayjs.utc().unix()
  ) {
    const accessToken = await redis.get<string>("PINTEREST_ACCESS_TOKEN");
    if (accessToken != null) {
      return accessToken;
    }
  }
  const auth = `${process.env.PINTEREST_APP_ID!}:${process.env
    .PINTEREST_SECRET_KEY!}`;
  const b64auth = Buffer.from(auth).toString("base64");
  const res = await axios.post<
    OAuthApiResponseBody,
    AxiosResponse<OAuthApiResponseBody>,
    OAuthApiRequestBody
  >(
    `${process.env.PINTEREST_API_URL!}/oauth/token`,
    {
      grant_type: "client_credentials",
      scope: "pins:read,pins:write,boards:read,boards:write",
    },
    {
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization: `Basic ${b64auth}`,
      },
    }
  );
  if (res.status < 200 || res.status > 299) {
    throw new Error(res.statusText);
  }
  await redis.set("PINTEREST_ACCESS_TOKEN", res.data.access_token);
  await redis.set(
    "PINTEREST_ACCESS_TOKEN_EXPIRES_AT",
    dayjs.utc().unix() + res.data.expires_in
  );
  return res.data.access_token;
};

type OAuthApiRequestBody = {
  grant_type: "client_credentials";
  scope: string;
};
type OAuthApiResponseBody = {
  access_token: string;
  response_type: "client_credentials";
  token_type: "bearer";
  expires_in: number;
  scope: string;
};
```
Notice that I first check my existing access token in redis and if it is expired, then I generate a new one. Also, the ENV variable for the api url is for the sandbox -> `https://api-sandbox.pinterest.com/v5`

Here is the code I use to save a board
```typescript
const saveBoard = async ({
  accessToken,
  description,
  title,
}: {
  accessToken: string;
  title: string;
  description: string;
}) => {
  const boardRes = await axios.post<
    PinterestBoardsApiRes,
    AxiosResponse<PinterestBoardsApiRes>,
    PinterestBoardsApiBody
  >(
    `${process.env.PINTEREST_API_URL!}/boards`,
    {
      name: title,
      description: description,
      privacy: "PUBLIC",
    },
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    }
  );
  console.log(boardRes.status);
  console.log(boardRes.statusText);
  console.log(boardRes.data);
  if (boardRes.status < 200 || boardRes.status > 299) {
    throw new Error(boardRes.statusText);
  }
  return boardRes.data.id;
};
```

I am not sure what it is that I am doing wrong. The error I get is `{ code: 2, message: 'Authentication failed.' }` and it is very ambiguous.

**Comment by davidchaiken** [comment]
Hello and thanks for using the Pinterest API! I tested the same scenario using the code in this repo, and (based on my tests) think that client credentials might not work with the Create board (POST https://api*.pinterest.com/v5/boards) endpoint yet. Let me check with the development team and get back to you.

**Comment by davidchaiken** [comment]
The development team confirms that they haven't yet implemented support for client credentials with the Create board endpoint. If they decide to release this feature, I'll let you know.

**Comment by muezz** [comment]
@davidchaiken I see. That is a bit disappointing since the docs mention this (and this repo too) but they never mentioned this being a work in progress. At least I did not see any indication of that.

That being said, is there any other way to achieve something like this? The only other way I can think of is using something like puppeteer to "fake" a user interacting with the auth screen. But that might be against Pinterest ToS and they may reject the standard access request.

For context, my use case is only for marketing. Users DO NOT interact with pinterest at all. The content generated by the users is posted in pinterest in my (personal) brand label account under various boards.

I do not mind having to update my access token manually in redis every 30 days too but Pinterest support asks for the user authentication screen to be visible in the video.

Any suggestions?

**Comment by davidchaiken** [comment]
The development team is acting kind of like a start-up in this area: favoring early release of incomplete functionality, and then filling in the blanks as developers make requests. In this case, you're request has been heard and the responsible engineers seems pretty enthusiastic about meeting this need. Speaking of which, are there any other endpoints that you need to support your use case?

I think that the code in this repo demonstrates one way to achieve your goal: pull a token manually and then save it in a convenient place. This repo saves the token on the local file system, which admittedly isn't very secure and should really just be used in development mode. Redis (with appropriate access controls) sounds like a fine alternative.

**Comment by muezz** [comment]
@davidchaiken My use case is fairly straightforward. My users generate content and that content needs to be posted on Pinterest on an automated basis. At the moment, I only need write functionality for pins and boards. 

It would be great if you could tell me how far along this functionality is from being developed. Or how could I check if it has been developed.

**Comment by davidchaiken** [comment]
PR posted, awaiting tests and review. Once tests and review pass, automated deployment will take it to production as quickly as possible. I'll let you know when that's done.

That's about as close as we can get to operating as quickly as a start-up, given that there are now more than half a billion Pinterest users.

**Comment by muezz** [comment]
That is great. I did not expect it to happen this quickly so I really appreciate it.

**Comment by davidchaiken** [comment]
Yep. I love this development team. That's what I meant by "acting like a start-up" -- responding rapidly to developer requests rather than working on big waterfall-style roadmaps.

The functionality is now available in production. I tested creating Pins & boards with client credentials and it now works for me. Please let us know if you need anything else for your use case. Otherwise, we'll keep working towards more global support for client credentials as a background task.

**Comment by muezz** [comment]
@davidchaiken Thanks for the quick response on this. I just checked it out and it is working perfectly. I am submitting the video now. Hopefully it gets approved for standard access.
