### ISSUE TITLE
Using Script for Multiple Accounts After Obtaining Standard Access

### ISSUE THREAD

**Issue by Pyswann** [pinterest/api-quickstart#131]
I have created a script using the trial API that allows me to upload multiple pins at once with better SEO optimization. However, I now want to obtain Standard Access and am making a video to get this.

My question is, if I get access from an account, can I use the same script for my second account to get access?

**Comment by davidchaiken** [comment]
Thanks for the developing on the Pinterest API! Can you say a bit more about the "second account?" How is it related to the first account?

**Comment by Pyswann** [comment]
Hi, thanks for your kind reply! I built the app for my team, and we generally work for clients who want to reach the right audience on Pinterest. Hence, we need to use multiple Pinterest accounts.
