### ISSUE TITLE
Missing support for query_parameters in User.get_boards (nodejs)

### ISSUE THREAD

**Issue by christophlocher** [pinterest/api-quickstart#26]
Hi there!

First of all, thanks for creating these thorough examples and very helpful API objects – it is an unbelievable improvement over the previous versions of the Pinterest API. Great Job!

One thing I noticed in the nodejs code is that while [`User.get_boards`](https://github.com/pinterest/api-quickstart/blob/main/nodejs/src/v5/user.js#L30-L40) supports the query parameters, [`Board.get_pins`](https://github.com/pinterest/api-quickstart/blob/main/nodejs/src/v5/board.js#L18-L20) does not.

I’love to see support for them here, since setting [page_size](https://developers.pinterest.com/docs/api/v5/#operation/boards/list_pins) is especially valuable when getting a board’s pins, since it is likely there are many and it can be valuable to reduce the number of API calls.

**Comment by davidchaiken** [comment]
Yes, I agree. I'm doing a bit of refactoring and implementing the feature uniformly for all endpoints. Will let you know when there is a branch and/or PR ready.
