### ISSUE TITLE
Pinterest API is always asking for permissions

### ISSUE THREAD

**Issue by epsilongithub** [pinterest/api-quickstart#28]
I am using the NodeJS version of the API, and everytime I execute a script, for example get_analytics.js, I am redirected to developers.pinterest.com and have to give permission.
I have my APP_ID and API_SECRET configured and `env | grep PINTEREST_APP` returns them correctly.
Why is this happening?

**Comment by davidchaiken** [comment]
Hi, @epsilongithub. I'm closing this issue, but please feel free to reach out with additional questions and/or feedback for us.
