### ISSUE TITLE
How to deploy the Python Implementation?

### ISSUE THREAD

**Issue by patricker** [pinterest/api-quickstart#42]
Do you see people installing the client library through a dependency system like `pip`?
I'm just about ready to deploy the Python quickstart as part of a Python data pipeline, but I'm not really sure how to setup the dependency.

I tried doing something like this:
```
pip install "git+https://github.com/pinterest/api-quickstart.git#egg=pinterestads&subdirectory=python"
```

But it doesn't actually make the code available.

I tried setting up my own setup.cfg in my own branch, but I probably made a mistake, I couldn't get it to work either.

**Comment by davidchaiken** [comment]
That's a great question, @patricker. We're discussing internally at Pinterest, and I'll do my best to respond early next week.

**Comment by patricker** [comment]
Great, looking forward to hearing back from you then.

**Comment by davidchaiken** [comment]
Hi, @patricker.

The development team discussed your suggestion at our mid-sprint meeting today. Here's how we're thinking...

In the future, we plan to release a software development toolkit (SDK) that is versioned and installable as a package. This SDK will be mostly autogenerated from the OpenAPI description of PInterest's API: https://github.com/pinterest/api-description

The quickstart in this repo, however, is not intended to be versioned and supported as a package. It's mostly for educational purposes, and our approach is to make it open source for transparency and ease-of-use. While you're welcome to use the code, we decided not to facilitate installation as a client library.

**Comment by patricker** [comment]
While not the answer I was hoping for, understood.
I've copied over the necessary quick start code into my project and it's working.
