### ISSUE TITLE
Translate a Pinterest Ad Analytics UI Query into an API Query?

### ISSUE THREAD

**Issue by patricker** [pinterest/api-quickstart#46]
I have a user who is showing me in the Pinterest Ads Analytics Web UI a query. Now I need to extract that same data using the API.
For some data this has been very easy, but I can't come up with a consistent way to translate what I'm seeing on screen to an API call.

I started by using Chrome developer tools to view the request, and trying to extract the column names to then use in the API. But the column names don't match up.

For example, I'm querying "Total view-through conversions (Lead)" in the Web UI, which translates to "TOTAL_VIEW_LEAD" in the ... v4? API call. But this column does not exist in the v5 API, and I get an error if I pass it in.

Here are four specific columns that I can query in the Web UI, that it's not quite clear to me how to query through the v5 API.

        "TOTAL_OUTBOUND_CLICK",
        "TOTAL_CLICK_LEAD",
        "TOTAL_ENGAGEMENT_LEAD",
        "TOTAL_VIEW_LEAD",

**Comment by jquittograham** [comment]
Hello @patricker thank you for bringing this issue up! Although I do not know the answer right now, I will investigate this further and follow-up with possible solutions or updates!

**Comment by jquittograham** [comment]
@patricker Of course! I will get back to you when the new features are available!

**Comment by jquittograham** [comment]
@umar6542003 Hello Umar, our team is still working on making our metrics consistent with what is provided in the docs. Timeline wise, we will have an update within the next couple of weeks. 

Thanks again for your patience and feedback.

**Comment by jquittograham** [comment]
Hello @patricker @umar6542003 ,

I am pleased to inform you that we have just released our new v5 API today and have updated our async ads_reporting endpoint which now includes the TOTAL_CLICK_LEAD, TOTAL_ENGAGEMENT_LEAD, and TOTAL_VIEW_LEAD metrics. Please let me know if you have anymore questions or updates. 

Thanks again!
