### ISSUE TITLE
Metrics existence and metrics paramters divergence between platform and API(v5 and v4)

### ISSUE THREAD

**Issue by victorfmartins** [pinterest/api-quickstart#50]
Hi,

Me and my team are having some difficulties using your API. My fellow analysts want to use metrics that exist in your platform, but those same metrics are not available through the API, which makes the process more manual. The metrics are: conversion page visit, conversion add to card, paid pin clicks, and paid saves (as named in the platform).

Also, there are parameters in some metrics that are available in the API, but are different from the platform. We are especially concerned with the total order value (checkout) metric, which for the click/engagement/view parameter assignment we can access the 7/0/0 in the platform, but with the API we can only access highers than 7/1/1.

Could you help us with these? Thanks
Victor Martins,

**Comment by jquittograham** [comment]
Hello @victorfmartins, 

Thank you for taking your time to use our API and offer feedback! Our team did notice some inconsistencies with the metrics available in our docs vs what our API provides and are working on fixing those issues. We should have an update in within the next couple weeks.

Thank you

**Comment by victorfmartins** [comment]
Hi, @jquittograham 

I appreciate your return, thank you. 
I will be waiting for the update then, good job for you.

Cheers

**Comment by jquittograham** [comment]
Hello,
I am pleased to inform you that we have just released version v5.3.0 of our API today which includes a new ads reporting endpoint https://developers.pinterest.com/docs/api/v5/. The specific metrics you asked about, as well as many more, are available through this new endpoint. Please let me know if you have anymore questions or updates.
Thanks again!
