### ISSUE TITLE
Migration guide from V4 to V5?

### ISSUE THREAD

**Issue by chrizi42** [pinterest/api-quickstart#66]
Hi, would it be possible to get a migration guide for going from V4 to V5? The migration guide for V3 to V4 was very helpful and it would be great to get something similar for V5.

We are especially interested in going from the following V4 endpoints to their new V5 counterparts:

- https://api.pinterest.com/ads/v4/advertisers/{advertiser_id}/campaigns
- https://api.pinterest.com/ads/v4/advertisers
- https://api.pinterest.com/ads/v4/advertisers/{advertiser_id}/delivery_metrics/async
- https://api.pinterest.com/ads/v4/advertisers/{advertiser_id}/ads/{ad_id}

Maybe these aren't available yet or are some of them here: https://developers.pinterest.com/docs/api/v5/#tag/ad_accounts ?

**Comment by davidchaiken** [comment]
Good question! I'll ask around to see what I can find out. (It might take until sometime next week to get back to you.)

**Comment by davidchaiken** [comment]
Hi, @chrizi42. Here's the inside scoop from the developers at Pinterest... The team is planning to write a v4 to v5 development guide. Right now, they're working hard on some new functionality, and plan to release the guide and the new features at the same time.
