### ISSUE TITLE
Issue migrating to v5 for existing endpoints from v3.       

### ISSUE THREAD

**Issue by mattnwa** [pinterest/api-quickstart#69]
Hi!

Me and my team are having some difficulties using the v5 API. We are migrating from v3 and are missing a few critical metrics that don't seem to be in v5. The metrics we're noticing missing include. 

- User follower_count (v3/users/me/) 

- Pin summary metrics like engagements although the documentation mentions them in the response samples. (/v5/pins/id/analytics)

We want to migrate to the new version at the same time to move scopes to the new v5. 

<img width="1554" alt="Screen Shot 2022-08-01 at 7 45 15 PM" src="https://user-images.githubusercontent.com/13283053/182280664-357e28ab-1eaf-49c4-8709-01737972aec1.png">

Could you help us with these? Thanks
Matt

**Comment by davidchaiken** [comment]
Thanks for your questions about the v5 API, Matt. I'll see what our API product & marketing folks have to say and get back to you.

**Comment by mattnwa** [comment]
Thank you! We assumed the pins /analytics and user /analytics endpoints would be consistent so it's caused some confusion.

**Comment by davidchaiken** [comment]
Sorry for the delay in responding! I'll ping our product & marketing folks again...

**Comment by davidchaiken** [comment]
Hello @mattnwa! Sorry for the delay in my response. Here's what our product team says...

1. The issue with Pin summary metrics sounds like a bug. We would appreciate it if you would file a ticket in our Help Center: https://help.pinterest.com/en/contact (I just looked at this page and think that `Pinterest API and Developer Tools / API Technical Support / Pinterest API v5` will get you to the right place.)
2. We're still working internally to figure out follower_count. I'll try to remember to post to this issue again if I see progress internally.
