### ISSUE TITLE
Pins published by trial applications shouldn't count

### ISSUE THREAD

**Issue by alef-ru** [pinterest/api-quickstart#72]
I spot a minor bug in Pinterest's backend. It's not related to the code in this repository, but I haven't found a better place to report it.

Steps to reproduce:
1. created an app with Trial access
2. created a board and a section manually
3. create several pins over API in the board/section using the app
4. Check, how it looks for another user / anonymous user

Expected result:
1. No pins in the section and board shown
2. The number of pins in the section and the board is 0

Actual result
1. No pins in the section and board shown ✅
2. The number of pins >0. Even though the user cannot see these pins ⚠️

**Comment by davidchaiken** [comment]
Thanks for the bug report. I'll file it in Pinterest's internal Jira system. In the future, you can report bugs in our Help Center: https://help.pinterest.com/en/contact (I just looked at this page and think that `Pinterest API and Developer Tools / API Technical Support / Pinterest API v5` will get you to the right place.)

**Comment by davidchaiken** [comment]
Closing this issue, because it's not related to this repo.
