### ISSUE TITLE
What's the alternative to `resources/delivery_metrics`?

### ISSUE THREAD

**Issue by nbro10** [pinterest/api-quickstart#74]
[This example](https://github.com/pinterest/api-quickstart/blob/main/python/src/v5/delivery_metrics.py) states that we can no longer query the definitions of the metrics with v5. So, what are the alternatives now? I suppose [this](https://github.com/pinterest/api-description) could be useful, but I wonder why the endpoint is no longer available in v5 and what the recommended way to replace this endpoint is.

**Comment by davidchaiken** [comment]
Thanks for the question! I'll ask the team how we're planning to make metrics definitions available and get back to you...

**Comment by davidchaiken** [comment]
The development team says that the `/v5/resources/delivery_metrics` endpoint that you need is implemented, working in in our preproduction environments, and should be released by the end of the month. I'll try to remember to send an update when it's available.

**Comment by davidchaiken** [comment]
Hello! It look like our development team is moving along with the functionality that they promised. My bet is that beta endpoints require some sort of special access. I'll check to find out...

**Comment by davidchaiken** [comment]
@nbro10, beta access is handled manually by our partner management team. If you send me (chaiken@pinterest.com) enough information to identify your app (company name should do it, maybe app id, but definitely **not** the app secret), I can send the information over to them. Or if you want to go through official channels, you can submit a ticket at https://help.pinterest.com/en/contact (I think that `Pinterest API and Developer Tools / API Technical Support / Pinterest API v5` will get you to the right place.)

**Comment by davidchaiken** [comment]
...and our tech writer points out [this documentation](https://developers.pinterest.com/docs/new/changelog/#Beta%20releases) on getting access to Beta features.

**Comment by davidchaiken** [comment]
@nbro10 GET /v5/resources/delivery_metrics is now generally available, so I'm going to add support for this endpoint to the quickstart. In the meantime, the documentation of the endpoint is [here](https://developers.pinterest.com/docs/api/v5/#operation/delivery_metrics/get).
