### ISSUE TITLE
Specify `report_status` values

### ISSUE THREAD

**Issue by IzeBerg** [pinterest/api-quickstart#76]
Asynchronous reports API does not have a specification of values that `report_stats` can be.

https://developers.pinterest.com/docs/api/v5/#operation/analytics/get_report
https://github.com/pinterest/api-quickstart/blob/main/python/src/async_report.py

**Comment by davidchaiken** [comment]
Good point! I'll ask the Pinterest Development Platform technical documentation expert for their advice on the best way to address this need.

**Comment by davidchaiken** [comment]
I discussed with the documentation expert and the development team, and we agree that we should provide a specification for the values of `report_status`. I opened a task for the team to do this work.

In the meantime, I found the complete list of status values in our API code...
```
class JobStatusValues(Enum):
    # All possible status values for bulk reporting jobs stored here
    DOES_NOT_EXIST = 'DOES_NOT_EXIST'
    FINISHED = 'FINISHED'
    IN_PROGRESS = 'IN_PROGRESS'
    EXPIRED = 'EXPIRED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
```
It will probably take us some time to grep the code to make sure that we understand the exact meaning of these values and release this information as part of the API specification.

**Comment by renat-iliev-cndt** [comment]
Thanks a lot!
