### ISSUE TITLE
OAuth redirect not working :(

### ISSUE THREAD

**Issue by dhruv1711** [pinterest/api-quickstart#77]
Hello all,

I just installed the environment on my WSL after testing it successfully on my Macbook. When I execute the get_access_token file, it redirects to the OAuth page properly on my Macbook, but when I do the same on my WSL, I get the following error:

```
(api) iyerd@DESKTOP-G13PG0K:/mnt/c/Users/iyerd/api-quickstart/python$ python3 ./scripts/get_access_token.py
Using application ID and secret from PINTEREST_APP_ID and PINTEREST_APP_SECRET.
reading access_token_v5 from environment failed, trying read
reading access_token_v5 failed, trying oauth
v5 requires scopes for OAuth. setting to default: READ_USERS,READ_PINS,READ_BOARDS
getting auth_code...



Traceback (most recent call last):
  File "/mnt/c/Users/iyerd/api-quickstart/python/./scripts/get_access_token.py", line 115, in <module>
    main(sys.argv[1:])
  File "/mnt/c/Users/iyerd/api-quickstart/python/./scripts/get_access_token.py", line 78, in main
    access_token.fetch()
  File "/mnt/c/Users/iyerd/api-quickstart/python/src/access_token_common.py", line 53, in fetch
    self.oauth(scopes=scopes, refreshable=refreshable)
  File "/mnt/c/Users/iyerd/api-quickstart/python/src/v5/access_token.py", line 33, in oauth
    auth_code = get_auth_code(
  File "/mnt/c/Users/iyerd/api-quickstart/python/src/user_auth.py", line 117, in get_auth_code
    return httpServer.auth_code
AttributeError: 'HTTPServer' object has no attribute 'auth_code'
```

Can you please guide me on how to go about solving this error? I have a feeling that the python version plays a part.
Thanks in advance!
Dhruv

**Comment by davidchaiken** [comment]
Hi, Dhruv.

We've only tried the quickstart with MacOS and Ubuntu Linux -- not WSL yet. To debug this problem, I'd set a debugger breakpoint in user_auth:do_GET and verify that `auth_code` is set on line 46. It's also possible that the browser start-up preempts the python thread, triggering the race condition documented on line 88.

You could also consider changing to the nodejs (JavaScript) version of the quickstart.

Please let me know if you make any progress debugging on WSL. I'd be happy to review a pull request that fixes this issue!
