### ISSUE TITLE
Ad account created not available from get ad_accounts in v5

### ISSUE THREAD

**Issue by EpicPantz** [pinterest/api-quickstart#84]
Hello, 
In version 4 account created time is available from the get advertisers endpoint, but the new get ad_accounts in version 5 does not offer this. How do we retrieve the accounts created date in v5?

**Comment by davidchaiken** [comment]
Thanks for the feedback! We'll see what we can do to get the created time added to v5. No promises, but the API team at Pinterest is really excited to work to make sure that the API meets your needs.

(I'm going to close this issue because your comment is on the API, not on the code in this repo.)

**Comment by davidchaiken** [comment]
@EpicPantz The team at Pinterest was excited to get your feedback, and rolled out the feature that you requested. You should find `created_time` and `updated_time` fields in the response to `/v5/ad_accounts`.

@chrizi42 Thanks for the <3. :)

**Comment by EpicPantz** [comment]
Wow this is amazing! 
Thank you and forward my gratitude to the development team!
