### ISSUE TITLE
500 on Two Promoted Products endpoints

### ISSUE THREAD

**Issue by ericmartell** [pinterest/api-quickstart#85]
Hi all!

We're integrating with Pinterest and are hitting a bug on the following.  Stubbed out authorization.

```
curl -X GET -L \
 -H 'Authorization: Bearer XYZ' \
 --compressed \
 'https://api.pinterest.com/v5/ad_accounts/549765284349/product_group_promotions?ad_group_id=2680074608081&entity_statuses=ACTIVE&order=ASCENDING';

{"code":12,"message":"Something went wrong on our end. Sorry about that."}
```

Getting the same looking up product group promotions by id:
```

curl -X GET -L \
 -H 'Authorization: Bearer XYZ' \
 --compressed \
 'https://api.pinterest.com/v5/ad_accounts/549765284349/product_group_promotions/4260608094066';

{"code":12,"message":"Something went wrong on our end. Sorry about that."}

```
--

Also fyi pinterest-api@pinterest.com bounces back but is listed on https://developer.pinterest.com/docs/api/v5/

Thanks for looking into this!

**Comment by davidchaiken** [comment]
Thanks for the feedback! I'll check with the engineering team on those errors. Also, thanks for letting us know about the issue with pinterest-api@.

**Comment by davidchaiken** [comment]
Follow-up... The Pinterest Engineering team has opened up internal tickets to fix these issues. Since neither are related to the code in this repo, I'm going to close this issue. I'll try to remember to send an update when I see that the issues are resolved.

**Comment by davidchaiken** [comment]
Hello! Here are the resolution of these issues:
1. The development team says that they fixed the 500 errors.
2. We removed pinterest-api@pinterest.com from our documentation.
